apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-app
  template:
    metadata:
      labels:
        app: task-app
    spec:
      containers:
        - name: task-backend
          image: eshariaz1/backend:latest  # Backend image from Docker Hub
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URI
              value: "mongodb+srv://esha:esha123@cluster0.ypvzn.mongodb.net/scdproject?retryWrites=true&w=majority"  # Correct MongoDB URI
        - name: task-frontend
          image: eshariaz1/frontend:latest  # Frontend image from Docker Hub
          imagePullPolicy: Always
          ports:
            - containerPort: 80  # Changed to 80 for Nginx
